"""add ai platform tables (ai_tasks/ai_feedback/ai_alerts)

Revision ID: 5dd5dc80fb22
Revises: c3a35cc6c606
Create Date: 2026-06-13 08:16:40.529738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5dd5dc80fb22'
down_revision: Union[str, None] = 'c3a35cc6c606'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_alerts',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('level', sa.String(length=8), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('action_url', sa.String(length=512), nullable=True),
    sa.Column('action_label', sa.String(length=64), nullable=True),
    sa.Column('object_type', sa.String(length=32), nullable=True),
    sa.Column('object_id', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('dismiss_remark', sa.Text(), nullable=True),
    sa.Column('snooze_until', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ai_alerts_user_status', 'ai_alerts', ['user_id', 'status', 'created_at'], unique=False)
    op.create_index(op.f('ix_ai_alerts_created_at'), 'ai_alerts', ['created_at'], unique=False)
    op.create_table('ai_feedback',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False),
    sa.Column('target_type', sa.String(length=32), nullable=False),
    sa.Column('target_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('rating', sa.String(length=8), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ai_feedback_target', 'ai_feedback', ['target_type', 'target_id'], unique=False)
    op.create_index('idx_ai_feedback_user', 'ai_feedback', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_ai_feedback_created_at'), 'ai_feedback', ['created_at'], unique=False)
    op.create_table('ai_tasks',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('task_id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('sub_type', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('progress', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('total_count', sa.Integer(), nullable=False),
    sa.Column('done_count', sa.Integer(), nullable=False),
    sa.Column('failed_count', sa.Integer(), nullable=False),
    sa.Column('input', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('output', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('cost_cents', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=True),
    sa.Column('model_version', sa.String(length=32), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('ai_trace_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ai_tasks_tenant_status', 'ai_tasks', ['tenant_id', 'status'], unique=False)
    op.create_index('idx_ai_tasks_type_created', 'ai_tasks', ['type', 'created_at'], unique=False)
    op.create_index(op.f('ix_ai_tasks_created_at'), 'ai_tasks', ['created_at'], unique=False)
    op.create_index(op.f('ix_ai_tasks_task_id'), 'ai_tasks', ['task_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_tasks_task_id'), table_name='ai_tasks')
    op.drop_index(op.f('ix_ai_tasks_created_at'), table_name='ai_tasks')
    op.drop_index('idx_ai_tasks_type_created', table_name='ai_tasks')
    op.drop_index('idx_ai_tasks_tenant_status', table_name='ai_tasks')
    op.drop_table('ai_tasks')
    op.drop_index(op.f('ix_ai_feedback_created_at'), table_name='ai_feedback')
    op.drop_index('idx_ai_feedback_user', table_name='ai_feedback')
    op.drop_index('idx_ai_feedback_target', table_name='ai_feedback')
    op.drop_table('ai_feedback')
    op.drop_index(op.f('ix_ai_alerts_created_at'), table_name='ai_alerts')
    op.drop_index('idx_ai_alerts_user_status', table_name='ai_alerts')
    op.drop_table('ai_alerts')
    # ### end Alembic commands ###
