"""add resource_code to audit_logs

Revision ID: c3a35cc6c606
Revises: 1670dd8259da
Create Date: 2026-06-13 08:12:17.527593

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3a35cc6c606'
down_revision: Union[str, None] = '1670dd8259da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_logs', sa.Column('resource_code', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_audit_logs_resource_code'), 'audit_logs', ['resource_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_logs_resource_code'), table_name='audit_logs')
    op.drop_column('audit_logs', 'resource_code')
    # ### end Alembic commands ###
